#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Edilson Alzemand

import pip
import sys
import os

comand = sys.argv[1:]
qr = ' '.join(comand)

def install(pack):
    pip.main(['install', pack])

try: import pyqrcode
except:
    print('PyQRCode not found, wait for the installation ...\n')
    install('pyqrcode')
import pyqrcode

text = qr

if not text:
    print('ubi: I not found text\n')
    exit()
else:
    arq = pyqrcode.create(text)
    arq.svg('/tmp/qrcode-ubi.svg', scale = 5)


