#!/usr/bin/env python

import pygame
pygame.init()

song = pygame.mixer.Sound('/usr/share/ubi/lib/sound/ubi-search.ogg')
clock = pygame.time.Clock()
song.play()
while True:
    clock.tick(0.5)
    break
pygame.quit()
