#!/usr/bin/env python

import sys
import pygame

comand = sys.argv[1:]
enter = ' '.join(comand)

pygame.init()

if enter == 'search':
    song = pygame.mixer.Sound('/usr/share/ubi/lib/sound/ubi-search.ogg')
    clock = pygame.time.Clock()
    song.play()
    while True:
        clock.tick(0.5)
        break
    pygame.quit()

elif enter == 'delay':
    song = pygame.mixer.Sound('/usr/share/ubi/lib/sound/ubi-delay.ogg')
    clock = pygame.time.Clock()
    song.play()
    while True:
        clock.tick(0.5)
        break
    pygame.quit()

elif enter == 'ubi':
    song = pygame.mixer.Sound('/usr/share/ubi/lib/sound/ubi.ogg')
    clock = pygame.time.Clock()
    song.play()
    while True:
        clock.tick(0.2)
        break
    pygame.quit()
